# Generated by Django 4.0.2 on 2022-02-27 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0003_alter_customuserchannel_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_channels', models.ManyToManyField(blank=True, null=True, related_name='follow_channels', to='auser.CustomUserChannel')),
                ('follow_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
