# Generated by Django 4.0.2 on 2022-02-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0004_followchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followchannel',
            name='follow_channels',
            field=models.ManyToManyField(blank=True, related_name='follow_channels', to='auser.CustomUserChannel'),
        ),
    ]
