# Generated by Django 4.0.2 on 2022-02-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auser', '0003_alter_customuserchannel_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('describe', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('owner_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_channel', to='auser.customuserchannel')),
            ],
        ),
    ]
