# Generated by Django 4.0.2 on 2022-03-07 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('describe', models.TextField(blank=True, null=True)),
                ('file_video', models.FileField(upload_to='videos/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('owner_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_channel', to='auser.customuserchannel')),
            ],
        ),
        migrations.CreateModel(
            name='ViewLikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='video_content_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='video_content_like', to=settings.AUTH_USER_MODEL)),
                ('video_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_content_ldv_user', to='content.videocontent')),
                ('views', models.ManyToManyField(blank=True, related_name='video_content_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_proxy', models.FileField(upload_to='videos/')),
                ('size', models.IntegerField()),
                ('frame', models.IntegerField()),
                ('original_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_proxy', to='content.videocontent')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.comment')),
                ('video_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.videocontent')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
