# Generated by Django 4.0.2 on 2022-03-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproxy',
            name='name',
        ),
    ]
