# Generated by Django 4.0.2 on 2022-02-28 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewLikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='video_content_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='video_content_like', to=settings.AUTH_USER_MODEL)),
                ('video_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_content_ldv_user', to='content.videocontent')),
                ('views', models.ManyToManyField(blank=True, related_name='video_content_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
